"""Eight executable cells; default offline and no scripted human approval."""
def notebook():
    cells=[]
    def add(kind,text):
        row={'id':f'cell-{len(cells):02d}','cell_type':kind,'metadata':{},'source':text.splitlines(keepends=True)}
        if kind=='code': row.update(execution_count=None,outputs=[])
        cells.append(row)
    def md(text): add('markdown',text)
    def code(text): add('code',text)
    md('# پروژهٔ دستیار پیگیری پرونده — معماری دوم\n\nراهنما: این نوت‌بوک مانند تمرین‌ها، داده، چانک، کش، بازیابی ترکیبی، بازرتبه‌بندی، تولید، داوری و اقدام با تأیید انسانی را جدا نشان می‌دهد. حالت پیش‌فرض رایگان است. امبدینگ و داور آفلاین، بدل آزمایشی‌اند و کیفیت مدل واقعی را ثابت نمی‌کنند.')
    code("from pathlib import Path\nimport sys, json, subprocess, tempfile, hashlib\nROOT = Path.cwd()\nassert (ROOT / 'src/casepilot').exists(), 'نوت‌بوک را از ریشهٔ پروژه اجرا کنید.'\nsys.path.insert(0, str(ROOT / 'src'))\nfrom casepilot.common import read_json\nfrom casepilot.store import Store\nfrom casepilot.agent import Agent\nfrom casepilot.model import ReplayClient\nfrom casepilot.retrieval import Retriever\nfrom casepilot.hybrid import HybridRetriever\nprint('وضعیت: معماری دوم؛ اجرای پیش‌فرض بدون شبکه است.')")
    md('## مرحلهٔ داده و چانک‌سازی\n\nتوضیح: ایندکس جدید از همان منابع غربال‌شده ساخته می‌شود. خانواده‌های ارزیابی و پاراگراف‌های پاسخ مستقیم وارد آن نمی‌شوند. عنوان، بخش، خط، نسخه و هش حفظ می‌شوند. کد و جدول بلوک اتمی‌اند؛ بلوک بیش‌ازحد بزرگ هنگام بسته‌بندی شاهد کنار می‌رود. تخمین توکن با شمار بایت محافظه‌کارانه است.')
    code("index = read_json(ROOT / 'data/index_v2_manifest.json')\nassert hashlib.sha256((ROOT / 'data/corpus_v2.json').read_bytes()).hexdigest() == index['corpus_sha256']\nprint(json.dumps(index, ensure_ascii=False, indent=2))\nprint('توضیح: ایندکس ثابت موجود خوانده شد؛ ساخت دوباره اختیاری با ابزار build_index.py است و صورت قفل ارزیابی را تغییر می‌دهد.')")
    md('## مرحلهٔ بازیابی ترکیبی و کش\n\nتوضیح: جست‌وجوی واژگانی با امبدینگ واقعی در حالت زنده ترکیب می‌شود. ادغام رتبه با `RRF`، تنوع با `MMR` و هشدار نسخه اجرا می‌شوند. کش به متن نرمال‌شده و مدل وابسته است. در حالت زنده، ساخت کامل ایندکس یک مرحلهٔ مستقل و محدود است؛ هر پرسش فقط امبدینگ پرسش را می‌سازد.')
    code("client = ReplayClient()\nretriever = HybridRetriever(client)\nquery = 'session_state widget value resets after navigation'\nfor method, rows in [('baseline', Retriever().search(query, method='baseline')), ('hybrid_fixture', retriever.search(query, k=8, version='1.49.0'))]:\n    print('روش:', method, [(r['source_id'], r['section']) for r in rows[:5]])\nretriever.search(query, k=8)\nprint('وضعیت کش پرسش تکراری:', retriever.last_trace['embedding'])\nassert retriever.last_trace['embedding']['batches'] == 0")
    md('## مرحلهٔ تولید، داوری و گفت‌وگو\n\nتوضیح: نقش‌های استخراج، بازرتبه‌بندی، تولید و داوری فراخوانی‌های جدا دارند. نسخهٔ اصلاح کیفیت، برنامهٔ تشخیص را در همان استخراج تولید می‌کند؛ گزارش اولیه، اصلاحات تازه و آزمایش‌های قبلی به زمینه می‌روند. منابع اداری فیلتر می‌شوند. داور برای ادعا و شاهد، عبارت واقعی پاسخ و دلیل پشتیبانی، و برای سؤال دلیل تازه‌بودن می‌دهد؛ کنترل کد قرارداد نامعتبر را رد می‌کند. بازنویسی جست‌وجوی فارسی حداکثر یک بار است. اصلاح حداکثر یک بار و با داوری دوباره انجام می‌شود. شکست به ارجاع امن می‌رسد. داور مدل جای بازبین انسانی نیست.')
    code("temporary = tempfile.TemporaryDirectory(prefix='casepilot-v2-notebook-')\nstore = Store(Path(temporary.name) / 'tracker.sqlite3')\nagent = Agent(store=store, client=client, hybrid=retriever)\nfirst = agent.turn('notebook-case', 'مقدار session_state پس از جابه‌جایی صفحه تغییر می‌کند.', 'nb-v2-1')\nsecond = agent.turn('notebook-case', 'پاسخ: نسخه مشخص شد و نمونهٔ کوچک هم رفتار را دارد.', 'nb-v2-2', facts={'streamlit_version':'1.49.0','reproducible':True})\nprint(second['response'])\nprint('مسیر اجرا:', [s['stage'] for s in second['pipeline']])\nprint('داوری آزمایشی:', second['judge'])\nassert second['model_calls'] <= 8 and second['repair_count'] <= 1\nassert not store.get('notebook-case')['comments']")
    md('## مرحلهٔ بازبینی انسانی و اقدام\n\nراهنما: متن و شاهدها را بخوانید و تصمیم را خودتان عوض کنید. پیش‌فرض رد است. تأیید به همین پرونده، هش و نسخهٔ پیشنهاد وابسته است؛ ویرایش یا اطلاعات تازه تأیید قبلی را نامعتبر می‌کند.')
    code("REVIEW_DECISION = 'reject'\np = second['proposal']\nreview = store.review('notebook-case', p['id'], p['hash'], REVIEW_DECISION, 'بازبین نوت‌بوک')\nif REVIEW_DECISION == 'approve':\n    result = store.execute('notebook-case', p['id'], review['approval_id'])\n    assert store.execute('notebook-case', p['id'], review['approval_id'])['replayed']\n    print(result)\nelse:\n    assert not store.get('notebook-case')['comments']\n    print('وضعیت: پیشنهاد رد شد و نظر ثبت نشد.')")
    md('## مرحلهٔ آزمون و ارزیابی توسعه\n\nتوضیح: آزمون‌ها خطاهای قرارداد، کش، بودجه، داور، اصلاح، استناد و مجوز را پوشش می‌دهند. مقایسهٔ حذف مؤلفه‌ها در ابزار ارزیابی فراهم است. ارزیابی آفلاین معیار کیفیت مدل نیست. آزمون قبلی دیده شده است؛ ادعای کیفیت نهایی معماری دوم به آزمون تازه و بازبینی مستقل نیاز دارد.')
    code("subprocess.run([sys.executable, 'scripts/run_tests.py'], cwd=ROOT, check=True)\nconfiguration = hashlib.sha256(b''.join(p.read_bytes() for p in sorted((ROOT / 'src/casepilot').glob('*.py')))).hexdigest()[:12]\nlabel = 'notebook_' + configuration\nfolder = ROOT / 'artifacts/architecture_v2/offline' / (label + '_full')\nif not (folder / 'manifest.json').exists():\n    subprocess.run([sys.executable, 'scripts/evaluate_v2.py', '--limit', '15', '--label', label], cwd=ROOT, check=True)\nprint('نتیجهٔ توسعهٔ آفلاین:', read_json(folder / 'manifest.json')['complete'])")
    md('## مرحلهٔ کنترل خصمانه\n\nتوضیح: آزمون‌های مرز مجوز و نقل‌قولِ نسخهٔ اول حفظ شده‌اند؛ آزمون‌های معماری دوم، خروجی جعلی داور و بازرتبه‌بند، شکست داوری و توقف پس از یک اصلاح را جدا بررسی می‌کنند. این‌ها ادعای مقاومت مدل واقعی در برابر همهٔ تزریق‌ها نیستند.')
    code("subprocess.run([sys.executable, 'scripts/adversarial.py'], cwd=ROOT, check=True)\nprint('نتیجهٔ کنترل‌های قطعی:', read_json(ROOT / 'artifacts/test_results.json'))")
    md('## مرحلهٔ اجرای واقعی محدود\n\nراهنما: کلید فقط در محیط فرایند باشد. اجرای زیر پیش‌فرض خاموش است. ساخت ایندکس سقف هشت سنت و نمونهٔ توسعه سقف هفت سنت دارد. راهنمای اجرا و تعرفه در مستندات آمده است. ارزیابی واقعی نسخهٔ اول و آزمایش معماری دوم نتایج جدا هستند.')
    code("RUN_LIVE = False\nif RUN_LIVE:\n    raise RuntimeError('برای اجرای پولی تازه، دفتر مشترک و سقف را طبق راهنمای اجرای واقعی بررسی کنید؛ ارزیابی ثابت را تکرار نکنید.')\nelse:\n    saved = ROOT / 'artifacts/quality_revision/final_evaluation/completion_manifest.json'\n    print('وضعیت: هیچ درخواست واقعی تازه‌ای اجرا نشد.')\n    if saved.exists():\n        measured = read_json(saved)\n        semantic = read_json(saved.parent / 'ai_review_manifest.json')\n        print('ارزیابی اصلاح کیفیت:', measured['complete'], 'مقایسه‌ها:', measured['attempted_comparisons'])\n        print('سناریوهای عملیاتی:', measured['scenarios'])\n        print('کیفیت معنایی؛ قضاوت هوش مصنوعی:', semantic['summary'])\n        print('هزینهٔ افزودهٔ ارزیابی:', measured['new_charged_or_reserved_usd'])\n    print('توضیح: نتیجه‌های معماری‌های قبلی تاریخی‌اند؛ مرور آن‌ها رایگان است. فرم انسانی خالی است.')\ntemporary.cleanup()")
    return {'cells':cells,'metadata':{'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'},'language_info':{'name':'python','version':'3.11'}},'nbformat':4,'nbformat_minor':5}
